In [1]:
from  google.colab import drive  
drive.mount('/content/drive')
%cd /content/drive/My\ Drive/algo trading/stocks
### save and load data using pickle
import pickle
def psave(dataframe, fname):
    with open('{}.pkl'.format(fname),'wb') as pickle_file:
        pickle.dump(dataframe,pickle_file)
        
def pload(fname):
  
  with open('{}.pkl'.format(fname),'rb') as pickle_file:
      dataframe=pickle.load(pickle_file)
      return dataframe

Mounted at /content/drive
/content/drive/My Drive/algo trading/stocks

In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import math as mt
import datetime

from itertools import product
import sys

In [4]:
sys.path.append("/content/drive/MyDrive/Colab Notebooks/classes")
%reload_ext autoreload
%autoreload 2
from trading_main import account
from PropertyTest_DataGeneration import Gen as g
from DfPlot import dp

/usr/local/lib/python3.7/dist-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm

In [5]:
train_s=np.datetime64('2013-12-30')
train_e=np.datetime64('2017-12-29')

vali_s=np.datetime64('2018-01-02')
vali_e=np.datetime64('2018-12-31')

test_s=np.datetime64('2019-01-02')
test_e=np.datetime64('2019-12-30')
df=pload('selectedpairs_LSTM')

df = df.rename(columns={'return': 'ret'})

In [6]:
StockData=pload('StockPool')

In [8]:
#calculating the LSTM forecasted return on the validation set
length=len(df.iloc[0]['LSTM_vali'])

returnlstm=[]
for i in range(len(df)):
  r=[]
  sp=df.iloc[i]['spread'].loc[vali_s:vali_e]
  for j in range(length-1):
    r.append((df.iloc[i]['LSTM_vali'].iloc[j+1]-sp.iloc[j])/sp.iloc[j])


  inde=sp.iloc[:-1].index
  rr=pd.Series(r,index=inde)
  returnlstm.append(rr)

In [9]:
df['LSTM_vali_return']=returnlstm

In [30]:
#calculate the variance of the actual return on the training, validation set and the forecasted return on the validation set
v={'train_var':[],'vali_var':[],'LSTM_vali_var':[]}
for i in range(20):

  v['LSTM_vali_var'].append(df.iloc[i]['LSTM_vali_return'].var())
  v['vali_var'].append(df.iloc[i]['ret'].loc[vali_s:vali_e].var())
  v['train_var'].append(df.iloc[i]['ret'].loc[train_s:train_e].var())

In [31]:
d=pload('LSTM_result')
for i in v:
  d[i]=v[i]

In [32]:
d

        cross      mean1  ...    vali_var  LSTM_vali_var
363082     37 -33.884243  ...    0.010816       0.000695
99348      33 -17.050050  ...    0.005211       0.000139
288449     36 -27.130426  ...    0.456656       0.043044
216234     35  -2.241410  ...    0.000913       0.000110
314459     91   3.059907  ...    0.004051       0.000720
363238     32  -6.491330  ...   35.513797       3.029029
365248     38  -5.172277  ...    3.490920       3.244509
288537     40   2.226178  ...    0.003136       0.000068
439897     34  -1.855255  ...  174.453168      86.485471
99073      34 -10.444400  ...    0.001211       0.000040
343879     53  10.455164  ...    0.000935       0.000048
213032     36 -22.203382  ...    0.000730       0.000084
363116     32 -21.616234  ...  381.777443       2.775072
370108     33  -4.390121  ...    0.001919       0.000190
299691     47   2.282393  ...    0.002822       0.000162
370078     40  -8.746139  ...    0.000997       0.000026
215806     71  15.386518  ...    0.000111       0.000011
403782     34 -19.360815  ...    0.007802       0.000367
374562     45 -73.893814  ...    0.002054       0.000100
343984     40   8.920654  ...    0.000823       0.000018

[20 rows x 27 columns]

In [33]:
d['tv_diff']=d['train_var']-d['vali_var']

In [34]:
#variance between acutual return of training data and validation data
d.sort_values('tv_diff')

        cross      mean1  ... LSTM_vali_var       tv_diff
363116     32 -21.616234  ...      2.775072 -2.219616e+02
439897     34  -1.855255  ...     86.485471 -1.713023e+02
363238     32  -6.491330  ...      3.029029 -2.402270e+01
314459     91   3.059907  ...      0.000720 -1.247848e-03
343879     53  10.455164  ...      0.000048  1.777051e-05
215806     71  15.386518  ...      0.000011  3.501145e-05
374562     45 -73.893814  ...      0.000100  3.493411e-04
216234     35  -2.241410  ...      0.000110  4.093519e-04
343984     40   8.920654  ...      0.000018  5.999614e-04
370078     40  -8.746139  ...      0.000026  7.108550e-04
370108     33  -4.390121  ...      0.000190  1.007719e-03
299691     47   2.282393  ...      0.000162  1.034079e-03
213032     36 -22.203382  ...      0.000084  2.725847e-03
99073      34 -10.444400  ...      0.000040  3.270887e-03
403782     34 -19.360815  ...      0.000367  1.844811e+00
363082     37 -33.884243  ...      0.000695  2.078792e+00
288537     40   2.226178  ...      0.000068  2.302402e+00
365248     38  -5.172277  ...      3.244509  3.444553e+00
99348      33 -17.050050  ...      0.000139  6.177027e+00
288449     36 -27.130426  ...      0.043044  5.443592e+08

[20 rows x 28 columns]

In [36]:
d['tv_diff_abs']=abs(d['train_var']-d['vali_var'])

In [38]:
#sort the difference's absolute value
d.sort_values('tv_diff_abs')

        cross      mean1  ...       tv_diff   tv_diff_abs
343879     53  10.455164  ...  1.777051e-05  1.777051e-05
215806     71  15.386518  ...  3.501145e-05  3.501145e-05
374562     45 -73.893814  ...  3.493411e-04  3.493411e-04
216234     35  -2.241410  ...  4.093519e-04  4.093519e-04
343984     40   8.920654  ...  5.999614e-04  5.999614e-04
370078     40  -8.746139  ...  7.108550e-04  7.108550e-04
370108     33  -4.390121  ...  1.007719e-03  1.007719e-03
299691     47   2.282393  ...  1.034079e-03  1.034079e-03
314459     91   3.059907  ... -1.247848e-03  1.247848e-03
213032     36 -22.203382  ...  2.725847e-03  2.725847e-03
99073      34 -10.444400  ...  3.270887e-03  3.270887e-03
403782     34 -19.360815  ...  1.844811e+00  1.844811e+00
363082     37 -33.884243  ...  2.078792e+00  2.078792e+00
288537     40   2.226178  ...  2.302402e+00  2.302402e+00
365248     38  -5.172277  ...  3.444553e+00  3.444553e+00
99348      33 -17.050050  ...  6.177027e+00  6.177027e+00
363238     32  -6.491330  ... -2.402270e+01  2.402270e+01
439897     34  -1.855255  ... -1.713023e+02  1.713023e+02
363116     32 -21.616234  ... -2.219616e+02  2.219616e+02
288449     36 -27.130426  ...  5.443592e+08  5.443592e+08

[20 rows x 29 columns]

In [50]:
#mean mse on the validation set
d['LSTM_mse'].mean()

0.035336614889092746

In [39]:
d['LSTM_mse'].describe()

count    20.000000
mean      0.035337
std       0.021585
min       0.002326
25%       0.021556
50%       0.037977
75%       0.055867
max       0.062894
Name: LSTM_mse, dtype: float64

In [43]:
newd=d.loc[d['para']!=()]

In [47]:
#mean rate of return using the LSTM forecast
d['LSTM_testreturn'].sum()/16

0.3307940128691494

In [49]:
d['LSTM_testreturn'].describe()

count    20.000000
mean      0.264635
std       0.535478
min      -0.166363
25%       0.000000
50%       0.000000
75%       0.285002
max       1.862351
Name: LSTM_testreturn, dtype: float64

In [53]:
#number of profitable pair
len(d.index[d['LSTM_testreturn']>0])

7

In [54]:
#number of unprofitable pair
len(d.index[d['LSTM_testreturn']<0])

4

In [58]:
#total number of trades
d['LSTM_testtime'].sum()

33.0

In [59]:
#total number of unprofitable trades
d['LSTM_losetime'].sum()

12

In [63]:
#difference between variance of the actural return and LSTM forecasted return on the validation set
d['vv_diff']=d['vali_var']-d['LSTM_vali_var']

In [64]:
d['vv_diff'].describe()

count     20.000000
mean      25.007780
std       85.817684
min        0.000099
25%        0.000950
50%        0.002864
75%        0.069193
max      379.002371
Name: vv_diff, dtype: float64

In [66]:
d.sort_values('vv_diff')

        cross      mean1            pair  ...   tv_diff_abs vv_diff_abs     vv_diff
215806     71  15.386518   [TCBIL, ZIXI]  ...  3.501145e-05    0.000099    0.000099
213032     36 -22.203382   [BPOPN, CASS]  ...  2.725847e-03    0.000645    0.000645
216234     35  -2.241410  [TCBIL, VLGEA]  ...  4.093519e-04    0.000802    0.000802
343984     40   8.920654    [PBPB, SREV]  ...  5.999614e-04    0.000804    0.000804
343879     53  10.455164    [PBPB, ZNGA]  ...  1.777051e-05    0.000887    0.000887
370078     40  -8.746139    [DAKT, EPZM]  ...  7.108550e-04    0.000971    0.000971
99073      34 -10.444400    [AVNW, EPZM]  ...  3.270887e-03    0.001171    0.001171
370108     33  -4.390121     [DAKT, GSM]  ...  1.007719e-03    0.001729    0.001729
374562     45 -73.893814    [DSPG, NXPI]  ...  3.493411e-04    0.001954    0.001954
299691     47   2.282393    [CWCO, PFLT]  ...  1.034079e-03    0.002660    0.002660
288537     40   2.226178   [VOXX, MARPS]  ...  2.302402e+00    0.003068    0.003068
314459     91   3.059907    [FDUS, MGIC]  ...  1.247848e-03    0.003331    0.003331
99348      33 -17.050050    [AVNW, MMYT]  ...  6.177027e+00    0.005072    0.005072
403782     34 -19.360815    [FTEK, GPRE]  ...  1.844811e+00    0.007436    0.007436
363082     37 -33.884243    [CTHR, HAYN]  ...  2.078792e+00    0.010121    0.010121
365248     38  -5.172277     [TGA, CCLP]  ...  3.444553e+00    0.246411    0.246411
288449     36 -27.130426    [VOXX, NTCT]  ...  5.443592e+08    0.413612    0.413612
363238     32  -6.491330    [CTHR, CCLP]  ...  2.402270e+01   32.484767   32.484767
439897     34  -1.855255    [MIND, CCLP]  ...  1.713023e+02   87.967697   87.967697
363116     32 -21.616234    [CTHR, SWIR]  ...  2.219616e+02  379.002371  379.002371

[20 rows x 31 columns]

In [69]:
num=[]
for i in range(20):
  n=len(d.iloc[i]['vali_record'])
  num.append(n)

In [71]:
d['vali_time']=num

In [73]:
#total number of trades on the validation set
d['vali_time'].sum()

1458

In [72]:
d.sort_values('vali_time')

        cross      mean1            pair  ...  vv_diff_abs     vv_diff vali_time
363082     37 -33.884243    [CTHR, HAYN]  ...     0.010121    0.010121         0
403782     34 -19.360815    [FTEK, GPRE]  ...     0.007436    0.007436         0
288449     36 -27.130426    [VOXX, NTCT]  ...     0.413612    0.413612         0
363116     32 -21.616234    [CTHR, SWIR]  ...   379.002371  379.002371         0
288537     40   2.226178   [VOXX, MARPS]  ...     0.003068    0.003068        67
370108     33  -4.390121     [DAKT, GSM]  ...     0.001729    0.001729        73
215806     71  15.386518   [TCBIL, ZIXI]  ...     0.000099    0.000099        77
370078     40  -8.746139    [DAKT, EPZM]  ...     0.000971    0.000971        79
439897     34  -1.855255    [MIND, CCLP]  ...    87.967697   87.967697        83
99073      34 -10.444400    [AVNW, EPZM]  ...     0.001171    0.001171        89
365248     38  -5.172277     [TGA, CCLP]  ...     0.246411    0.246411        89
343984     40   8.920654    [PBPB, SREV]  ...     0.000804    0.000804        89
363238     32  -6.491330    [CTHR, CCLP]  ...    32.484767   32.484767        91
213032     36 -22.203382   [BPOPN, CASS]  ...     0.000645    0.000645        95
299691     47   2.282393    [CWCO, PFLT]  ...     0.002660    0.002660        95
314459     91   3.059907    [FDUS, MGIC]  ...     0.003331    0.003331       103
99348      33 -17.050050    [AVNW, MMYT]  ...     0.005072    0.005072       103
343879     53  10.455164    [PBPB, ZNGA]  ...     0.000887    0.000887       107
374562     45 -73.893814    [DSPG, NXPI]  ...     0.001954    0.001954       107
216234     35  -2.241410  [TCBIL, VLGEA]  ...     0.000802    0.000802       111

[20 rows x 32 columns]